obstacle_range: 1.5
raytrace_range: 2.5
footprint: [[0.15, 0.21], [0.15, -0.21], [-0.15,-0.21], [-0.15, 0.21]]
#robot_radius: ir_of_robot
map_topic: /map
subscribe_to_updates: true
observation_sources: laser_scan_sensor
laser_scan_sensor: {sensor_frame: laser_frame, data_type: LaserScan, topic: scan, marking: true, clearing: true}
global_frame: map
robot_base_frame: base_link
always_send_full_costmap: true
# point_cloud_sensor: {sensor_frame: frame_name, data_type: PointCloud, topic: topic_name, marking: true, clearing: true}